name: commit

on: [push]

jobs:
  commit:
    name: commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install httplib
    - run: python commit.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
