name: commit

on: [push]

jobs:
  commit:
    name: commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "test file" > temp_file
        git checkout -b test-file
        git add .
        git commit -m 'adding test file'
        git push --set-upstream origin test-file
